create database soultech;


use soultech;


create table clientes(
ID_cl    varchar(13)   primary key,
NOMBRE_CL VARCHAR(30)  NOT NULL,
AM_CL    VARCHAR(30)   NOT NULL,
AP_CL    VARCHAR(30)   NOT NULL,
TEL_CL   VARCHAR(15)   NOT NULL,
RFC_CL   VARCHAR(20)   NOT NULL,
EMAIL_CL  VARCHAR(50)  NOT NULL,
PAYBACK_CL DOUBLE      NOT NULL,
ID_D      VARCHAR(10)  NOT NULL);
ALTER TABLE CLIENTES ADD FOREIGN KEY (ID_D) REFERENCES DIRECCIONES(ID_D); 
ALTER TABLE CLIENTES ADD UNIQUE (RFC_CL);
INSERT INTO `clientes` (`ID_CL`, `NOMBRE_CL`, `AM_CL`, `AP_CL`, `TEL_CL`, `RFC_CL`, `EMAIL_CL`, `PAYBACK_CL`, `ID_D`) VALUES ('1', 'abner', 'LIRA', 'SILVA', '7751449690', '123HSKHKJHKLHKJSAD', 'ABNERGMAIL.COM', '50', '1');

create table empleados(
ID_E    varchar(13) primary key,
NOMBRE_E  varchar(30)  not null,
AP_E      varchar(30)  not null,
AM_E    varchar(30)  not null,
TEL_E     varchar(15)  not null,
RFC_E    varchar(20)  NOT NULL,
CURP_E     varchar(20)  NOT NULL,
ID_D       varchar(13)  not null,
ID_B       VARCHAR(13)  NOT NULL,
ID_F       varchar(13)  not null,
NSS_E      varchar(20)  not null);
ALTER TABLE EMPLEADOS ADD FOREIGN KEY(ID_D) REFERENCES DIRECCIONES(ID_D);
ALTER TABLE EMPLEADOS ADD FOREIGN KEY(ID_B) REFERENCES DATOS_BANCO(ID_B);
ALTER TABLE EMPLEADOS ADD FOREIGN KEY(ID_F) REFERENCES FERRETERIA(ID_F);
ALTER TABLE EMPLEADOS ADD UNIQUE (RFC_E);
ALTER TABLE EMPLEADOS ADD UNIQUE (CURP_E);
INSERT INTO `empleados` (`ID_E`, `NOMBRE_E`, `AP_E`, `AM_E`, `TEL_E`, `RFC_E`, `CURP_E`, `ID_D`, `ID_B`, `ID_F`, `NSS_E`) VALUES ('2', 'jose', 'lira', 'silva', '7751449690', 'LSJDW', 'JSLKJDLASJKL', '2', '2', '1', '15456646');


create table direcciones(
ID_D  VARCHAR(13) PRIMARY KEY,
CALLE_D VARCHAR(30) NOT NULL,
COL_D  VARCHAR(30)  NOT NULL,
NO_INT_D  VARCHAR(10) NOT NULL,
NO_EXT_D VARCHAR(10) NOT NULL,
CD_D      VARCHAR(5)  NOT NULL,
CP_D      VARCHAR(20)  NOT NULL,
EDO_D     VARCHAR(20) NOT NULL);
INSERT INTO `direcciones` (`ID_D`, `CALLE_D`, `COL_D`, `NO_INT_D`, `NO_EXT_D`, `CD_D`, `CP_D`, `EDO_D`) VALUES ('4', 'MANSANOS', 'pavon', '45', '4', 'TULANCINGO', '54899', 'HIDALGO');

create table productos(
ID_P  VARCHAR(13)  PRIMARY KEY,
NOMBRE_p VARCHAR(30) NOT NULL,
TIPO_P   VARCHAR(20) NOT NULL,
MARCA_P  VARCHAR(20) NOT NULL,
SKU_p    VARCHAR(20) NOT NULL,
PRECIO   double      NOT  NULL);
ALTER TABLE PRODUCTOS ADD UNIQUE (SKU_P);
INSERT INTO `productos` (`ID_P`, `NOMBRE_P`, `TIPO_p`, `MARCA_p`, `SKU_P`, `PRECIO`) VALUES ('3', 'rondanas', 'material', 'truper', '45465465', '5');


create table usuarios(
ID_US  VARCHAR(13) PRIMARY KEY,
USERNAME_US  VARCHAR(15) NOT NULL,
PASSWORD_US TEXT  NOT NULL,
TIPO_US VARCHAR(20) NOT NULL,
ID_E VARCHAR(13) NOT NULL);
INSERT INTO `usuarios` (`ID_US`, `USERNAME_US`, `PASSWORD_US`, `TIPO_US`, `ID_E`) VALUES ('3', 'abnerliraAL', 'tidus1234', 'empleado', '2');

reate table datos_banco(
ID_B VARCHAR(13) PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
NO_CUENTA VARCHAR(20) NOT NULL);
INSERT INTO `datos_banco` (`ID_B`, `NOMBRE`, `NO_CUENTA`) VALUES ('2', 'azteca', '124568');


create table proveedores(
ID_PR VARCHAR(13) PRIMARY KEY,
NOMBRE_PR VARCHAR(30) NOT NULL,
ID_D VARCHAR(13) NOT NULL,
TEL_PR VARCHAR(15) NOT NULL,
EMAIL_PR VARCHAR(15) NOT NULL);
ALTER TABLE proveedores ADD FOREIGN KEY (ID_D) REFERENCES DIRECCIONES(ID_D);
INSERT INTO `proveedores` (`ID_PR`, `NOMBRE_PR`, `ID_D`, `TEL_PR`, `EMAIL_PR`) VALUES ('2', 'jose antonio', '3', '7751449868', 'JOSE@GMAIL.COM');

create table compras(
ID_CO VARCHAR(13) PRIMARY KEY,
ID_US VARCHAR(13) NOT NULL,
FECHA_CO VARCHAR(15) NOT NULL,
IMPORTE_CO  DOUBLE    NOT NULL,
ID_PR  VARCHAR(13) NOT NULL,
IVA_CO DOUBLE NOT NULL);
ALTER TABLE compras ADD FOREIGN KEY (ID_US) REFERENCES usuarios(ID_US);
ALTER TABLE compras ADD FOREIGN KEY(ID_PR) REFERENCES proveedores(ID_PR);
INSERT INTO `compras` (`ID_CO`, `ID_US`, `FECHA_CO`, `IMPORTE_CO`, `ID_PR`, `IVA_CO`) VALUES ('2', '2', '07//11/2018', '350', '2', '35.0');


create table ferreteria(
ID_F VARCHAR(13) PRIMARY KEY,
ID_E VARCHAR(13) NOT NULL,
ID_D VARCHAR(13) NOT NULL);
ALTER TABLE FERRETERIA ADD FOREIGN KEY (ID_E) REFERENCES EMPLEADOS(ID_E);
ALTER TABLE FERRETERIA ADD FOREIGN KEY (ID_D) REFERENCES DIRECCIONES(ID_D);


create table facturas(
ID_FA VARCHAR(13) PRIMARY KEY,
ID_CL VARCHAR(13) NOT NULL,
ID_US VARCHAR(13) NOT NULL,
ID_F VARCHAR(13) NOT NULL,
ID_V VARCHAR(13) NOT NULL);
ALTER TABLE FACTURAS ADD FOREIGN KEY (ID_v) REFERENCES VENTAS(ID_V);
INSERT INTO `facturas` (`ID_FA`, `ID_CL`, `ID_US`, `ID_F`, `ID_V`) VALUES ('1', '1', '1', '1', '1');

create table ventas_productos(
ID_VP VARCHAR(13)  PRIMARY KEY,
ID_V  VARCHAR(13) NOT NULL,
SUBTOTAL_VP  INT   NOT NULL,
ID_P  VARCHAR(13) NOT NULL,
CANTIDAD_CP INT   NOT NULL,);
ALTER TABLE ventas_productos ADD FOREIGN KEY (ID_v) REFERENCES VENTAS(ID_V);
ALTER TABLE ventas_productos ADD FOREIGN KEY (ID_P) REFERENCES PRODUCTOS(ID_P);
INSERT INTO `ventas_productos` (`ID_VP`, `ID_V`, `SUBTOTAL_VP`, `ID_P`, `CANTIDAD_CP`) VALUES ('1', '1', '134', '2', '15');

create table ferreteria_productos(
ID_FP   VARCHAR(13)  PRIMARY KEY,
ID_F    VARCHAR(13)  NOT NULL,
ID_P    VARCHAR(13)  NOT NULL,
EXISTENCIA_FP INT    NOT NULL);
INSERT INTO `ferreteria_productos` (`ID_FP`, `ID_F`, `ID_P`, `EXCISTENCIA_FP`) VALUES ('1', '1', '2', '10');


create table COMPRAS_PRODUCTOS(
ID_CP VARCHAR(13) PRIMARY KEY,
ID_CO VARCHAR(13) NOT NULL,
PRECIO_CP DOUBLE  NOT NULL,
ID_P VARCHAR(13) NOT NULL,
CANTIDAD_CP INT NOT NULL);

ALTER TABLE COMPRAS_PRODUCTOS ADD FOREIGN KEY (ID_P) REFERENCES PRODUCTOS(ID_P);

INSERT INTO `compras_productos` (`ID_CP`, `ID_CO`, `PRECIO_CP`, `ID_P`, `CANTIDAD_CP`) VALUES ('1', '1', '45', '1', '15');




