/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author TeddyBear
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Background = new javax.swing.JLabel();
        JMB_Menu = new javax.swing.JMenuBar();
        JM_Catalogos = new javax.swing.JMenu();
        JMI_Clientes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMI_Empleados = new javax.swing.JMenuItem();
        JMI_Proveedores = new javax.swing.JMenuItem();
        JMI_Productos = new javax.swing.JMenuItem();
        JMI_Usuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        getContentPane().add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        JM_Catalogos.setText("Catalogos");

        JMI_Clientes.setText("Clientes");
        JM_Catalogos.add(JMI_Clientes);

        jMenu1.setText("jMenu1");
        JM_Catalogos.add(jMenu1);

        JMI_Empleados.setText("Empleados");
        JM_Catalogos.add(JMI_Empleados);

        JMI_Proveedores.setText("Proveedores");
        JM_Catalogos.add(JMI_Proveedores);

        JMI_Productos.setText("Productos");
        JM_Catalogos.add(JMI_Productos);

        JMI_Usuarios.setText("Usuarios");
        JM_Catalogos.add(JMI_Usuarios);

        JMB_Menu.add(JM_Catalogos);

        setJMenuBar(JMB_Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Background;
    public javax.swing.JMenuBar JMB_Menu;
    public javax.swing.JMenuItem JMI_Clientes;
    public javax.swing.JMenuItem JMI_Empleados;
    public javax.swing.JMenuItem JMI_Productos;
    public javax.swing.JMenuItem JMI_Proveedores;
    public javax.swing.JMenuItem JMI_Usuarios;
    public javax.swing.JMenu JM_Catalogos;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
