/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewProductos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public ViewProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSP_Tabla = new javax.swing.JScrollPane();
        JT_Inventario = new javax.swing.JTable();
        JB_Eliminar = new javax.swing.JButton();
        JB_Modificar = new javax.swing.JButton();
        JB_Agregar = new javax.swing.JButton();
        JL_Productos = new javax.swing.JLabel();
        JL_Background = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1024, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_Inventario.setBackground(new java.awt.Color(255, 204, 51));
        JT_Inventario.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        JT_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "SKU", "Precio", "Marca", "Tipo", "Proveedor", "Cantidad"
            }
        ));
        JSP_Tabla.setViewportView(JT_Inventario);

        add(JSP_Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 82, 943, 340));

        JB_Eliminar.setBackground(new java.awt.Color(255, 153, 0));
        JB_Eliminar.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        JB_Eliminar.setText("Eliminar Producto");
        add(JB_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 244, -1));

        JB_Modificar.setBackground(new java.awt.Color(255, 153, 0));
        JB_Modificar.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        JB_Modificar.setText("Modificar Producto");
        add(JB_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 244, -1));

        JB_Agregar.setBackground(new java.awt.Color(255, 153, 0));
        JB_Agregar.setForeground(new java.awt.Color(255, 204, 51));
        JB_Agregar.setText("+");
        add(JB_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        JL_Productos.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JL_Productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventario.png"))); // NOI18N
        add(JL_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));

        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_Agregar;
    public javax.swing.JButton JB_Eliminar;
    public javax.swing.JButton JB_Modificar;
    private javax.swing.JLabel JL_Background;
    public javax.swing.JLabel JL_Productos;
    public javax.swing.JScrollPane JSP_Tabla;
    public javax.swing.JTable JT_Inventario;
    // End of variables declaration//GEN-END:variables
}
