/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Proveedores = new javax.swing.JTable();
        JB_AgregarProveedor = new javax.swing.JButton();
        JB_EliminarProveedor = new javax.swing.JButton();
        JB_ModificarProveedor = new javax.swing.JButton();
        JL_Proveedores = new javax.swing.JLabel();
        JL_Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_Proveedores.setBackground(new java.awt.Color(255, 204, 51));
        JT_Proveedores.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        JT_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirección", "Telefono", "E-Mail"
            }
        ));
        jScrollPane1.setViewportView(JT_Proveedores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 82, 943, 340));

        JB_AgregarProveedor.setBackground(new java.awt.Color(255, 153, 0));
        JB_AgregarProveedor.setForeground(new java.awt.Color(255, 204, 51));
        JB_AgregarProveedor.setText("+");
        add(JB_AgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        JB_EliminarProveedor.setBackground(new java.awt.Color(255, 153, 0));
        JB_EliminarProveedor.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JB_EliminarProveedor.setText("Eliminar Proveedor");
        add(JB_EliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 244, -1));

        JB_ModificarProveedor.setBackground(new java.awt.Color(255, 153, 0));
        JB_ModificarProveedor.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JB_ModificarProveedor.setText("Modificar Proveedor");
        add(JB_ModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 244, -1));

        JL_Proveedores.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JL_Proveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proveedores.png"))); // NOI18N
        add(JL_Proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));

        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_AgregarProveedor;
    public javax.swing.JButton JB_EliminarProveedor;
    public javax.swing.JButton JB_ModificarProveedor;
    private javax.swing.JLabel JL_Background;
    public javax.swing.JLabel JL_Proveedores;
    public javax.swing.JTable JT_Proveedores;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
