/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewDirecciones extends javax.swing.JPanel {

    /**
     * Creates new form ViewDirecciones
     */
    public ViewDirecciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Direcciones = new javax.swing.JTable();
        JB_AgregarDireccion = new javax.swing.JButton();
        JB_EliminarDirección = new javax.swing.JButton();
        JB_ModificarDireccion = new javax.swing.JButton();
        JL_Direcciones = new javax.swing.JLabel();
        JL_Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_Direcciones.setBackground(new java.awt.Color(255, 204, 51));
        JT_Direcciones.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        JT_Direcciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Calle", "Colonia", "No.Interior", "No.Exterior", "Código Postal", "Ciudad", "Estado"
            }
        ));
        jScrollPane1.setViewportView(JT_Direcciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 82, 943, 340));

        JB_AgregarDireccion.setBackground(new java.awt.Color(255, 153, 0));
        JB_AgregarDireccion.setForeground(new java.awt.Color(255, 204, 51));
        JB_AgregarDireccion.setText("+");
        add(JB_AgregarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        JB_EliminarDirección.setBackground(new java.awt.Color(255, 153, 0));
        JB_EliminarDirección.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JB_EliminarDirección.setText("Eliminar Dirección");
        add(JB_EliminarDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 244, -1));

        JB_ModificarDireccion.setBackground(new java.awt.Color(255, 153, 0));
        JB_ModificarDireccion.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JB_ModificarDireccion.setText("Modificar Dirección");
        add(JB_ModificarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 244, -1));

        JL_Direcciones.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JL_Direcciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Direcciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/direcciones.png"))); // NOI18N
        add(JL_Direcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));

        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_AgregarDireccion;
    public javax.swing.JButton JB_EliminarDirección;
    public javax.swing.JButton JB_ModificarDireccion;
    private javax.swing.JLabel JL_Background;
    public javax.swing.JLabel JL_Direcciones;
    public javax.swing.JTable JT_Direcciones;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
