/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form ViewUsuarios
     */
    public ViewUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Usuarios = new javax.swing.JTable();
        JB_AgregarUsuario = new javax.swing.JButton();
        JB_EliminarUsuario = new javax.swing.JButton();
        JB_ModificarUsuario = new javax.swing.JButton();
        JL_Usuarios = new javax.swing.JLabel();
        JL_Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_Usuarios.setBackground(new java.awt.Color(255, 204, 51));
        JT_Usuarios.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        JT_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre de usuario", "Tipo de usuario", "Nombre de Empleado", "Apellido Paterno", "Apellido Materno", "Telefono", "RFC"
            }
        ));
        jScrollPane1.setViewportView(JT_Usuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 82, 943, 340));

        JB_AgregarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        JB_AgregarUsuario.setForeground(new java.awt.Color(255, 204, 51));
        JB_AgregarUsuario.setText("+");
        add(JB_AgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        JB_EliminarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        JB_EliminarUsuario.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JB_EliminarUsuario.setText("Eliminar Usuario");
        add(JB_EliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 244, -1));

        JB_ModificarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        JB_ModificarUsuario.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JB_ModificarUsuario.setText("Modificar Usuario");
        add(JB_ModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 244, -1));

        JL_Usuarios.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        JL_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usuarios.png"))); // NOI18N
        add(JL_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));

        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_AgregarUsuario;
    public javax.swing.JButton JB_EliminarUsuario;
    public javax.swing.JButton JB_ModificarUsuario;
    private javax.swing.JLabel JL_Background;
    public javax.swing.JLabel JL_Usuarios;
    public javax.swing.JTable JT_Usuarios;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
