/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author TeddyBear
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Background = new javax.swing.JLabel();
        JMB_Menu = new javax.swing.JMenuBar();
        JM_Catalogos = new javax.swing.JMenu();
        JM_Clientes = new javax.swing.JMenu();
        JMI_VerClientes = new javax.swing.JMenuItem();
        JMI_EditarClientes = new javax.swing.JMenuItem();
        JM_Empleados = new javax.swing.JMenu();
        JMI_VerEmpleados = new javax.swing.JMenuItem();
        JMI_EditarEmpleados = new javax.swing.JMenuItem();
        JM_Productos = new javax.swing.JMenu();
        JMI_VerProductos = new javax.swing.JMenuItem();
        JMI_EditarProductos = new javax.swing.JMenuItem();
        JM_Proveedores = new javax.swing.JMenu();
        JMI_VerProveedores = new javax.swing.JMenuItem();
        JMI_EditarProveedores = new javax.swing.JMenuItem();
        JM_Sucursales = new javax.swing.JMenu();
        JMI_VerSucursales = new javax.swing.JMenuItem();
        JMI_EditarSucursales = new javax.swing.JMenuItem();
        JM_Usuarios = new javax.swing.JMenu();
        JMI_VerUsuarios = new javax.swing.JMenuItem();
        JMI_EditarUsuarios = new javax.swing.JMenuItem();
        JM_Operaciones = new javax.swing.JMenu();
        JMI_Compras = new javax.swing.JMenuItem();
        JMI_Ventas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        getContentPane().add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        JM_Catalogos.setText("Catalogos");

        JM_Clientes.setText("Clientes");

        JMI_VerClientes.setText("Ver registros");
        JM_Clientes.add(JMI_VerClientes);

        JMI_EditarClientes.setText("Editar registros");
        JM_Clientes.add(JMI_EditarClientes);

        JM_Catalogos.add(JM_Clientes);

        JM_Empleados.setText("Empleados");

        JMI_VerEmpleados.setText("Ver registros");
        JM_Empleados.add(JMI_VerEmpleados);

        JMI_EditarEmpleados.setText("Editar registros");
        JM_Empleados.add(JMI_EditarEmpleados);

        JM_Catalogos.add(JM_Empleados);

        JM_Productos.setText("Productos");

        JMI_VerProductos.setText("Ver registros");
        JM_Productos.add(JMI_VerProductos);

        JMI_EditarProductos.setText("Editar registros");
        JM_Productos.add(JMI_EditarProductos);

        JM_Catalogos.add(JM_Productos);

        JM_Proveedores.setText("Proveedores");

        JMI_VerProveedores.setText("Ver registros");
        JM_Proveedores.add(JMI_VerProveedores);

        JMI_EditarProveedores.setText("Editar registros");
        JM_Proveedores.add(JMI_EditarProveedores);

        JM_Catalogos.add(JM_Proveedores);

        JM_Sucursales.setText("Sucursales");

        JMI_VerSucursales.setText("Ver registros");
        JM_Sucursales.add(JMI_VerSucursales);

        JMI_EditarSucursales.setText("Editar registros");
        JM_Sucursales.add(JMI_EditarSucursales);

        JM_Catalogos.add(JM_Sucursales);

        JM_Usuarios.setText("Usuarios");

        JMI_VerUsuarios.setText("Ver registros");
        JM_Usuarios.add(JMI_VerUsuarios);

        JMI_EditarUsuarios.setText("Editar registros");
        JM_Usuarios.add(JMI_EditarUsuarios);

        JM_Catalogos.add(JM_Usuarios);

        JMB_Menu.add(JM_Catalogos);

        JM_Operaciones.setText("Operaciones");

        JMI_Compras.setText("Compras");
        JM_Operaciones.add(JMI_Compras);

        JMI_Ventas.setText("Ventas");
        JM_Operaciones.add(JMI_Ventas);

        JMB_Menu.add(JM_Operaciones);

        setJMenuBar(JMB_Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Background;
    public javax.swing.JMenuBar JMB_Menu;
    private javax.swing.JMenuItem JMI_Compras;
    public javax.swing.JMenuItem JMI_EditarClientes;
    public javax.swing.JMenuItem JMI_EditarEmpleados;
    public javax.swing.JMenuItem JMI_EditarProductos;
    public javax.swing.JMenuItem JMI_EditarProveedores;
    public javax.swing.JMenuItem JMI_EditarSucursales;
    public javax.swing.JMenuItem JMI_EditarUsuarios;
    private javax.swing.JMenuItem JMI_Ventas;
    public javax.swing.JMenuItem JMI_VerClientes;
    public javax.swing.JMenuItem JMI_VerEmpleados;
    public javax.swing.JMenuItem JMI_VerProductos;
    public javax.swing.JMenuItem JMI_VerProveedores;
    public javax.swing.JMenuItem JMI_VerSucursales;
    public javax.swing.JMenuItem JMI_VerUsuarios;
    public javax.swing.JMenu JM_Catalogos;
    private javax.swing.JMenu JM_Clientes;
    private javax.swing.JMenu JM_Empleados;
    private javax.swing.JMenu JM_Operaciones;
    private javax.swing.JMenu JM_Productos;
    private javax.swing.JMenu JM_Proveedores;
    private javax.swing.JMenu JM_Sucursales;
    private javax.swing.JMenu JM_Usuarios;
    // End of variables declaration//GEN-END:variables
}
