/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Juan Pablo
 */
public class ViewLogin extends javax.swing.JPanel {

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_Login = new javax.swing.JButton();
        JL_Password = new javax.swing.JLabel();
        JTF_User = new javax.swing.JTextField();
        JL_User = new javax.swing.JLabel();
        JPF_Password = new javax.swing.JPasswordField();
        JL_Icon = new javax.swing.JLabel();
        JB_Info = new javax.swing.JButton();
        JL_Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Login.setBackground(new java.awt.Color(0, 153, 153));
        JB_Login.setText("HECHO");
        add(JB_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        JL_Password.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JL_Password.setForeground(new java.awt.Color(255, 255, 255));
        JL_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Password.setText("Contaseña");
        add(JL_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, -1));

        JTF_User.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JTF_User.setText("ACME");
        add(JTF_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 180, 20));

        JL_User.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JL_User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_User.setText("Usuario");
        add(JL_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, -1));

        JPF_Password.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        JPF_Password.setText("jPasswordField1");
        add(JPF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 180, -1));

        JL_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personal.png"))); // NOI18N
        add(JL_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 60));

        JB_Info.setBackground(new java.awt.Color(0, 153, 153));
        JB_Info.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        JB_Info.setText("?");
        add(JB_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        JL_Background.setBackground(new java.awt.Color(255, 204, 0));
        JL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ACME.png"))); // NOI18N
        add(JL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_Info;
    public javax.swing.JButton JB_Login;
    private javax.swing.JLabel JL_Background;
    private javax.swing.JLabel JL_Icon;
    private javax.swing.JLabel JL_Password;
    private javax.swing.JLabel JL_User;
    public javax.swing.JPasswordField JPF_Password;
    public javax.swing.JTextField JTF_User;
    // End of variables declaration//GEN-END:variables
}
